/**
 * Bundled DEMO scripts — Phase 4.5 hardening (discoverability).
 *
 * Seeded into /projects/examples so players can read and run a clean, commented
 * example of each major subsystem without any developer knowledge. Distinct from
 * /projects/scripts (the working tools): these are teaching examples. Authored as
 * plain source here; the filesystem seed materialises them as editable files.
 *
 * All run non-interactively (no input()/forms), so they work from both the
 * Terminal (`run examples/<name>`) and BuckyCode "Run".
 */
export const EXAMPLE_DEMOS = {
    "profile_demo.py": "# profile_demo.py - read your operator identity (Phase 4.5 example)\n# Run:  run examples/profile_demo.py\ndescribe({\"name\": \"profile_demo.py\", \"description\": \"Show your operator profile.\", \"usage\": \"profile_demo.py\"})\n\nstatus.card(\"OPERATOR PROFILE\", {\n    \"level\": profile.level(),\n    \"prestige\": profile.prestige(),\n    \"coins\": profile.coins(),\n    \"bank\": profile.bank(),\n    \"networth\": profile.networth(),\n    \"reputation\": profile.reputation(),\n    \"items\": profile.inventory_count(),\n    \"exposures\": len(profile.exposures())\n})\norg = profile.organization()\nif org != None:\n    print(\"Organization:\", org[\"name\"])\nelse:\n    print(\"No organization.\")\n",
    "leaks_demo.py": "# leaks_demo.py - browse the OSINT leak archive (Phase 4.5 example)\ndescribe({\"name\": \"leaks_demo.py\", \"description\": \"List recent leaks and inspect an incident.\", \"usage\": \"leaks_demo.py [LEAK-id]\"})\n\nstats = leaks.statistics()\nprint(\"Incidents on record:\", stats.get(\"total_incidents\", 0))\n\nprint(\"Recent exposures:\")\nrows = []\nfor o in leaks.recent(8):\n    rows.append({\"handle\": o[\"handle\"], \"severity\": o[\"severity\"], \"incident\": o.get(\"incident_id\", \"?\")})\ntable.render(rows)\n\nif len(args) > 0:\n    inc = leaks.incident(args[0])\n    if inc != None:\n        status.card(\"INCIDENT \" + inc[\"incident_id\"], {\"title\": inc.get(\"title\", \"?\"), \"severity\": inc.get(\"severity\", \"?\")})\n    else:\n        print(\"No incident:\", args[0])\n",
    "organizations_demo.py": "# organizations_demo.py - explore the organisation registry (Phase 4.5 example)\ndescribe({\"name\": \"organizations_demo.py\", \"description\": \"List organisations and your affiliation.\", \"usage\": \"organizations_demo.py\"})\n\nrows = []\nfor o in orgs.leaderboard():\n    rows.append({\"org\": o[\"name\"], \"members\": o.get(\"members\", 0), \"reputation\": o.get(\"reputation\", 0)})\ntable.render(rows)\n\nmine = orgs.mine()\nif mine != None:\n    print(\"You are affiliated with:\", mine[\"name\"])\nelse:\n    print(\"You are unaffiliated.\")\n",
    "leaderboard_demo.py": "# leaderboard_demo.py - read the Grid rankings (Phase 4.5 example)\ndescribe({\"name\": \"leaderboard_demo.py\", \"description\": \"Show the richest and highest-level operators.\", \"usage\": \"leaderboard_demo.py\"})\n\nprint(\"Available boards:\", leaderboards.kinds())\n\nprint(\"Top by net worth:\")\nrows = []\nfor r in leaderboards.richest(5):\n    rows.append({\"rank\": r.get(\"rank\", \"?\"), \"operator\": r.get(\"user_id\", \"?\"), \"level\": r.get(\"level\", \"?\")})\ntable.render(rows)\n\nprint(\"Top by level:\")\nrows = []\nfor r in leaderboards.levels(5):\n    rows.append({\"rank\": r.get(\"rank\", \"?\"), \"operator\": r.get(\"user_id\", \"?\"), \"score\": r.get(\"score_value\", \"?\")})\ntable.render(rows)\n\nmyrank = leaderboards.rank(\"richest\")\nif myrank != None:\n    print(\"Your richest rank:\", myrank)\n",
    "reports_demo.py": "# reports_demo.py - build and export a report (Phase 4.5 example)\n# Try:  run examples/reports_demo.py --save:/projects/reports/top.txt\ndescribe({\"name\": \"reports_demo.py\", \"description\": \"Build a leaderboard report and save it.\", \"usage\": \"reports_demo.py [--save:<path>]\", \"options\": [\"--save:<path>\"]})\n\ntop = leaderboards.richest(5)\nbody = report.table(\"TOP OPERATORS (richest)\", top)\nprint(body)\n\nout = args.get(\"--save\", \"/projects/reports/leaderboard.txt\")\nsaved = report.save(out, body)\nprint(\"Saved report ->\", saved)\n\nreport.to_archives(\"leaderboard.json\", report.json(top))\nprint(\"Archived JSON snapshot to /projects/archives/leaderboard.json\")\n",
    "args_demo.py": "# args_demo.py - the script argument framework (Phase 4.5 example)\n# Try:  run examples/args_demo.py -u:123456 --save:out.txt --full\ndescribe({\n    \"name\": \"args_demo.py\",\n    \"description\": \"Demonstrate flag parsing: -u:ID, --save:PATH, --full.\",\n    \"usage\": \"args_demo.py -u:<id> [--save:<path>] [--full]\",\n    \"options\": [\"-u:<id>\", \"--save:<path>\", \"--full\"]\n})\n\nprint(\"Positional args:\", args.positional())\nprint(\"All flags:\", args.all())\nprint(\"User id (-u):\", args.get(\"-u\", \"none\"))\nprint(\"User id as int:\", args.int(\"-u\", 0))\nprint(\"Save path (--save):\", args.get(\"--save\", \"/projects/reports/out.txt\"))\nprint(\"Full mode (--full):\", args.bool(\"--full\"))\n",
    "help_demo.py": "# help_demo.py - discover the runtime from inside the VM (Phase 4.5 example)\ndescribe({\"name\": \"help_demo.py\", \"description\": \"Use dir() and help() to explore the API.\", \"usage\": \"help_demo.py\"})\n\nprint(\"Available modules:\", dir())\nprint(\"\")\nprint(\"profile functions:\", dir(profile))\nprint(\"\")\nhelp(profile)\nprint(\"\")\nhelp(\"leaderboards.richest\")\n",
};
