/**
 * Bundled example scripts — Phase 4.4, Part 17.
 *
 * Working operator tools seeded into /projects/scripts so an operator can run,
 * read and remix real examples immediately. Each runs under the sandboxed VM
 * interpreter using only the bucky.* standard library. Authored as plain source
 * here; the filesystem seed materialises them as editable files.
 */
export const EXAMPLE_SCRIPTS = {
    "menu.py": "# menu.py - interactive operator console (Phase 4.4)\n# Run from the Terminal:  ./menu.py   (input() needs the interactive Terminal)\n\ndef show_menu():\n    print(\"=================================\")\n    print(\" BUCKY OPERATOR CONSOLE\")\n    print(\"=================================\")\n    print(\"1. Scan recent leaks\")\n    print(\"2. Show my profile\")\n    print(\"3. Organization leaderboard\")\n    print(\"4. Exit\")\n\nrunning = True\nwhile running:\n    show_menu()\n    choice = input(\"Select option:\")\n    if choice == \"1\":\n        ops = leaks.latest(5)\n        print(\"Recent exposed operators:\", len(ops))\n        for o in ops:\n            print(\" -\", o[\"handle\"], \"(\" + o[\"severity\"] + \")\")\n    elif choice == \"2\":\n        print(\"Level:\", profile.level(), \" Coins:\", profile.coins())\n        org = profile.organization()\n        if org:\n            print(\"Org:\", org[\"name\"])\n    elif choice == \"3\":\n        rank = 1\n        for o in orgs.leaderboard():\n            print(rank, o[\"name\"], \"-\", o[\"members\"], \"members\")\n            rank = rank + 1\n    elif choice == \"4\":\n        print(\"Goodbye, operator.\")\n        running = False\n    else:\n        print(\"Unknown option:\", choice)\n",
    "leak_reporter.py": "# leak_reporter.py - export the current leak archive to /projects/reports\nimport json\n\ndescribe({\n    \"name\": \"leak_reporter.py\",\n    \"description\": \"Generate a leak-archive incident report.\",\n    \"usage\": \"leak_reporter.py [options]\",\n    \"options\": [\"--save:<path>\", \"--verbose\"]\n})\n\nverbose = args.has(\"--verbose\")\nout_txt = args.get(\"--save\", \"/projects/reports/leak_archive.txt\")\n\nstats = leaks.statistics()\nvictims = leaks.latest()\nprint(\"Leak incidents:\", stats.get(\"total_incidents\", 0))\nprint(\"Exposed operators:\", len(victims))\n\nlines = [\"LEAK ARCHIVE REPORT\", \"===================\"]\nfor v in victims:\n    lines.append(v[\"handle\"] + \" | \" + v[\"severity\"] + \" | \" + str(v.get(\"incident_id\", \"?\")))\n    if verbose:\n        print(\" +\", v[\"handle\"], v[\"severity\"])\n\nreport_text = \"\\n\".join(lines)\nfiles.write(out_txt, report_text)\njson.save(\"/projects/reports/leak_archive.json\", {\"incidents\": stats.get(\"total_incidents\", 0), \"operators\": len(victims), \"victims\": victims})\nprint(\"Saved\", out_txt)\nprint(\"Saved /projects/reports/leak_archive.json\")\n",
    "incident_scanner.py": "# incident_scanner.py - inspect one leak incident\nimport json\n\ndescribe({\n    \"name\": \"incident_scanner.py\",\n    \"description\": \"Inspect a leak incident and its affected operators.\",\n    \"usage\": \"incident_scanner.py <LEAK-id> [options]\",\n    \"options\": [\"--verbose\"]\n})\n\nif len(args) == 0:\n    print(\"Usage: incident_scanner.py <LEAK-id>\")\n    print(\"Known incidents:\")\n    for i in leaks.incidents():\n        print(\" -\", i[\"incident_id\"], i[\"title\"])\nelse:\n    target = args[0]\n    inc = leaks.incident(target)\n    if inc == None:\n        print(\"No incident found:\", target)\n    else:\n        print(\"Incident:\", inc[\"incident_id\"])\n        print(\"Title:\", inc.get(\"title\", \"?\"))\n        print(\"Severity:\", inc.get(\"severity\", \"?\"))\n        affected = leaks.search(target)\n        print(\"Affected operators:\", len(affected))\n        for o in affected:\n            print(\" -\", o[\"handle\"])\n",
    "profile_audit.py": "# profile_audit.py - generate an operator profile report\nimport json\n\ndescribe({\n    \"name\": \"profile_audit.py\",\n    \"description\": \"Audit your operator identity and economy.\",\n    \"usage\": \"profile_audit.py [options]\",\n    \"options\": [\"--save:<path>\"]\n})\n\nme = profile.me()\nreport = {\n    \"level\": profile.level(),\n    \"prestige\": me.get(\"prestige\", 0),\n    \"coins\": profile.coins(),\n    \"networth\": profile.networth(),\n    \"reputation\": profile.reputation(),\n    \"organization\": None,\n    \"inventory\": profile.inventory_count(),\n    \"exposures\": len(profile.exposures())\n}\norg = profile.organization()\nif org:\n    report[\"organization\"] = org[\"name\"]\n\nprint(\"=== OPERATOR PROFILE AUDIT ===\")\nprint(\"Level:\", report[\"level\"], \" Prestige:\", report[\"prestige\"])\nprint(\"Coins:\", report[\"coins\"], \" Networth:\", report[\"networth\"])\nprint(\"Reputation:\", report[\"reputation\"])\nprint(\"Organization:\", report[\"organization\"])\nprint(\"Inventory items:\", report[\"inventory\"])\nprint(\"Recorded exposures:\", report[\"exposures\"])\n\nout = args.get(\"--save\", \"/projects/reports/profile_audit.json\")\njson.save(out, report)\nprint(\"Saved\", out)\n",
    "org_lookup.py": "# org_lookup.py - look up an organization\ndescribe({\n    \"name\": \"org_lookup.py\",\n    \"description\": \"Look up an organization by id, name, or search term.\",\n    \"usage\": \"org_lookup.py <id|name|term>\",\n    \"options\": []\n})\n\nif len(args) == 0:\n    print(\"Organizations on record:\")\n    for o in orgs.list():\n        print(\" -\", o[\"id\"], \":\", o[\"name\"], \"(\" + str(o[\"members\"]) + \" members)\")\nelse:\n    q = args[0]\n    org = orgs.get(q)\n    if org == None:\n        found = orgs.search(q)\n        if len(found) == 0:\n            print(\"No organization matches:\", q)\n        else:\n            print(\"Matches for \" + q + \":\")\n            for o in found:\n                print(\" -\", o[\"name\"])\n    else:\n        print(\"Organization:\", org[\"name\"])\n        print(\"Tagline:\", org.get(\"tagline\", \"\"))\n        print(\"Members:\", org[\"members\"])\n        mine = orgs.current()\n        if mine and mine[\"id\"] == org[\"id\"]:\n            print(\"(this is your organization)\")\n",
    "watchlist_monitor.py": "# watchlist_monitor.py - track operators of interest against the leak archive\nimport json\n\npath = \"/projects/data/watchlist.json\"\n\nif not files.exists(path):\n    json.save(path, {\"handles\": [\"Tommy\", \"Nova\"]})\n    print(\"Created default watchlist at\", path)\n\nwatch = json.load(path)\nhandles = watch.get(\"handles\", [])\nprint(\"Watching\", len(handles), \"operators\")\n\nops = leaks.latest()\nhits = []\nfor h in handles:\n    for o in ops:\n        if o[\"handle\"] == h:\n            hits.append(h + \" -> \" + o[\"severity\"])\n\nif len(hits) == 0:\n    print(\"No watched operators in the current leak archive. Clear.\")\nelse:\n    print(\"ALERT: watched operators exposed:\")\n    for hit in hits:\n        print(\" -\", hit)\n\njson.save(\"/projects/reports/watchlist_status.json\", {\"watching\": handles, \"hits\": hits})\nprint(\"Saved /projects/reports/watchlist_status.json\")\n",
    "exposure_tracker.py": "# exposure_tracker.py - record a snapshot of my exposure count each run\nimport json\n\npath = \"/projects/data/exposure_tracker.json\"\nhistory = []\nif files.exists(path):\n    history = json.load(path)\n\ncount = len(profile.exposures())\nrun = len(history) + 1\nhistory.append({\"run\": run, \"exposures\": count, \"level\": profile.level()})\njson.save(path, history)\n\nprint(\"Exposure tracker - run\", run)\nprint(\"Current exposures:\", count)\nprint(\"History length:\", len(history))\nfor h in history:\n    print(\" run\", h[\"run\"], \"->\", h[\"exposures\"], \"exposures\")\n",

    // ----- Phase 4.5 examples ------------------------------------------------
    "process_demo.py": "# process_demo.py - inspect the VM process table (Phase 4.5)\ndescribe({\n    \"name\": \"process_demo.py\",\n    \"description\": \"Show this script's own process and the live process table.\",\n    \"usage\": \"process_demo.py\"\n})\n\nme = process.current()\nif me != None:\n    print(\"I am PID\", me[\"pid\"], \"running\", me[\"name\"])\n\nprint(\"Active processes:\", len(process.active()))\nrows = []\nfor p in process.list():\n    rows.append({\"pid\": p[\"pid\"], \"state\": p[\"state\"], \"name\": p[\"name\"]})\ntable.render(rows)\nprint(\"Totals:\", process.stats())\n",
    "inventory_demo.py": "# inventory_demo.py - list and search your inventory (Phase 4.5)\ndescribe({\"name\": \"inventory_demo.py\", \"description\": \"Inspect and search your operator inventory.\", \"usage\": \"inventory_demo.py [term]\"})\n\nprint(\"Total items:\", inventory.count())\nrows = []\nfor it in inventory.items():\n    if type(it) == \"dict\":\n        rows.append({\"item\": it.get(\"name\", \"?\"), \"qty\": it.get(\"quantity\", 1)})\n    else:\n        rows.append({\"item\": it, \"qty\": 1})\nif len(rows) > 0:\n    table.render(rows)\nelse:\n    print(\"Inventory is empty.\")\n\nif len(args) > 0:\n    found = inventory.search(args[0])\n    print(\"Matches for\", args[0], \":\", len(found))\n",
    "economy_demo.py": "# economy_demo.py - read-only economy snapshot (Phase 4.5)\ndescribe({\"name\": \"economy_demo.py\", \"description\": \"Show coins, bank, net worth and level.\", \"usage\": \"economy_demo.py\"})\n\nstatus.card(\"ECONOMY\", {\n    \"level\": profile.level(),\n    \"coins\": economy.balance(),\n    \"bank\": economy.bank(),\n    \"networth\": economy.networth()\n})\nprint(\"Transfers route through Discord - economy.transfer is not enabled in the VM yet.\")\n",
    "security_demo.py": "# security_demo.py - security posture report (Phase 4.5)\ndescribe({\"name\": \"security_demo.py\", \"description\": \"Report your security posture and exposures.\", \"usage\": \"security_demo.py\"})\n\ns = security.status()\nstatus.card(\"SECURITY POSTURE\", {\n    \"posture\": s[\"posture\"],\n    \"score\": s[\"score\"],\n    \"breached\": s[\"breached\"],\n    \"exposures\": s[\"exposures\"],\n    \"firewall\": s[\"firewall\"][\"enabled\"]\n})\nif security.breached():\n    notify(\"Security alert: operator exposed\", \"alert\")\nelse:\n    print(\"No active exposures detected.\")\n",
    "watchlist_demo.py": "# watchlist_demo.py - manage a watchlist and check it vs the leak archive (Phase 4.5)\ndescribe({\"name\": \"watchlist_demo.py\", \"description\": \"Add an operator to your watchlist and check exposures.\", \"usage\": \"watchlist_demo.py [handle]\"})\n\nif len(args) > 0:\n    watchlist.add_operator(args[0])\n    print(\"Now watching:\", args[0])\n\nwatching = watchlist.list(\"operators\")\nprint(\"Watched operators:\", len(watching))\nfor h in watching:\n    print(\" -\", h)\n\nhits = watchlist.check()\nif len(hits) == 0:\n    print(\"No watched entities in the current leak archive. Clear.\")\nelse:\n    print(\"ALERT: watched entities exposed:\")\n    rows = []\n    for hit in hits:\n        rows.append({\"category\": hit[\"category\"], \"value\": hit[\"value\"], \"severity\": hit.get(\"severity\", \"?\")})\n    table.render(rows)\n    notify(\"Watchlist: \" + str(len(hits)) + \" exposed\", \"warn\")\n",
    "report_demo.py": "# report_demo.py - build a report and export it (Phase 4.5)\ndescribe({\"name\": \"report_demo.py\", \"description\": \"Build a leaderboard report and export/archive it.\", \"usage\": \"report_demo.py\"})\n\ntop = leaderboards.top(\"richest\", 5)\nprint(\"Top operators by net worth:\", len(top))\nbody = report.table(\"TOP OPERATORS (richest)\", top)\nprint(body)\n\nsaved = report.to_reports(\"leaderboard.txt\", body)\nprint(\"Report saved ->\", saved)\narchived = report.to_archives(\"leaderboard.json\", report.json(top))\nprint(\"Archived ->\", archived)\n",
    "bruteforce_demo.py": "# bruteforce_demo.py - the gated bruteforce PROCESS framework (Phase 4.5, section 23)\n# Run from the Terminal:  ./bruteforce_demo.py   (uses menu/form input)\n# Bruteforce is a process: it requires the Discord HackBank item, respects the\n# cooldown, shows progress, and NEVER bypasses Discord authority.\ndescribe({\"name\": \"bruteforce_demo.py\", \"description\": \"Gated bruteforce process demo (menu, form, progress).\", \"usage\": \"bruteforce_demo.py\"})\n\nif not hackbank.owned():\n    print(\"Bruteforce unavailable - you do not own the Discord HackBank item.\")\n    print(\"Acquire it through Discord, then try again.\")\n    exit()\n\nif not hackbank.available():\n    print(\"Bruteforce on cooldown:\", hackbank.cooldown(), \"seconds remaining.\")\n    exit()\n\ntargets = [\"arcade-node\", \"relay-07\", \"vault-core\"]\nsel = menu.show(targets, \"Select a target\")\nname = \"arcade-node\"\nif sel != None:\n    name = sel[\"value\"]\n\nif not form.confirm(\"Bruteforce \" + name + \"?\"):\n    print(\"Aborted.\")\n    exit()\n\nprogress.start(\"Bruteforce \" + name, 100)\nn = 0\nwhile n < 100:\n    n = n + 25\n    progress.update(n)\nprogress.finish()\n\nprint(\"VM stage complete. The breach action is Discord-authoritative:\")\nprint(\"the VM would route hackbank.run(target) through the Discord bridge.\")\nprint(\"No bypasses - Discord remains the authority.\")\n",
};
